name: ingress-nginx controller build
on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      run_controller_build:
        description: 'Force controller build (only) to run'
        required: false
        type: boolean

jobs:
  build:
    permissions:
      contents: write
      packages: write

    name: Build
    runs-on: ubuntu-latest
    env:
        PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest
          platforms: ${{ env.PLATFORMS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-controller
        run: |
          echo "building images (assumes nginx container already built)..."
          export TAGNGINX=$(cat images/nginx/TAG)
          make BASE_IMAGE=ghcr.io/lsst-sqre/nginx:${TAGNGINX} clean-image release
  
